

services:
  # Based on Chris instructions
#  spark-py:
#    image: docker.io/bitnami/spark:latest
#    container_name: spark_container
#    command: /opt/spark/bin/pyspark
#    environment:
#      - SPARK_MODE=master
#    ports:
#      - "7077:7077"
#      - "8080:8080"
#    volumes:
#      - .venv:/spark_py_env/
#    restart: always

# Based on GPT instructions OPT A: Works and I can connect to the interpreter. Can run python commands in IDE
#  spark:
#    image: apache/spark-py:latest
#    container_name: pyspark_dev
#    command: /bin/bash  # Start with a shell for flexibility
#    volumes:
#      - .:/workspace # Mount the current directory
#    working_dir: /workspace
#    environment:
#      - PYSPARK_PYTHON=python3
#      - SPARK_HOME=/opt/spark
# BASED ON GPT instructions OPT B: Requires a custom image (See Dockerfile). It allows me to specify the python
#  libraries I need directly in the Dockerfile. You need to "build" the image first from the Dockerfile
#  spark:
#    build: .
#    container_name: pyspark_dev
#    tty: true
#    stdin_open: true
#    volumes:
#      - .:/workspace
#    environment:
#      - PYTHONPATH=/opt/venv/lib/python3.10/site-packages
#      - SPARK_HOME=/opt/spark
#      - PATH=/opt/venv/bin:$PATH
##    ports:
##      - "4040:4040"
##      - "8888:8888"
#    command: /bin/bash
#  python_spark_dev:   # Use this if you need to build the image
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    image: my_image_pyspark
#    container_name: python_spark_dev
#    volumes:
#      - .:/my_workdir
  python_spark_dev_prebuilt:
    image: my_image_pyspark
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: netflix_show_recommendation
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  mongo_data:
  pg_data:

